"""add manager_id to user table

Revision ID: 8f282ca34e96
Revises: 6076dccfe48e
Create Date: 2025-09-07 08:41:50.065901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f282ca34e96'
down_revision: Union[str, None] = '6076dccfe48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'manager_id')
    # ### end Alembic commands ###
